name: Align development with main

on:
  push:
    branches:
      - main

jobs:
  publish-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "development"
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Adding changes from bump
        run: git merge main

      - name: Push latest version
        run: git push origin ${{ github.ref_name }} --follow-tags
