name: bump-version-constellation

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version
        run: yarn workspace @blockchain-com/constellation version ${{ github.event.inputs.version }}

      - name: Adding changes from bump
        run: git add .

      - name: Commit bump
        run: git commit -m "Bumping package version (${{ github.event.inputs.version }})"

      - name: Push latest version
        run: git push origin ${{ github.ref_name }} --follow-tags
