name: Constellation bundle analyzer

on: [push, pull_request]

jobs:
  analyze-bundle-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "development"
          fetch-depth: 0

      - name: Install node.js v14.16
        uses: actions/setup-node@v2
        with:
          node-version: 14.16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build and analyze constellation
        run: yarn workspace @blockchain-com/constellation analize_bundle:json

      - name: Run bundle-stats
        uses: vio/bundle-stats-action@v1
        with:
          webpack-stats-path: "packages/constellation/stats.json"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
