name: Start @blockchain-com/icons release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "development"
          fetch-depth: 0

      - name: Install node.js v14.16
        uses: actions/setup-node@v2
        with:
          node-version: 14.16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build optimized icons
        run: yarn workspace @blockchain-com/icons build

      - name: Bump version
        run: yarn workspace @blockchain-com/icons version ${{ github.event.inputs.version }}

      - name: Get Icons package version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "packages/icons/package.json"
          prop_path: "version"

      - name: Adding changes from bump
        run: git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: release @blockchain-com/icons@v${{ steps.version.outputs.prop }}
          title: Release @blockchain-com/icons@v${{ steps.version.outputs.prop }}
          body: Credit new contributors by updating AUTHORS
          branch: release/icons-v${{ steps.version.outputs.prop }}
          base: main
