name: Publish Constellation to NPM

on:
  push:
    branches:
      - main

jobs:
  publish-icons:
    if: github.event.pull_request.merged && startsWith(github.ref_name, 'release/constellation-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node.js v14.16
        uses: actions/setup-node@v2
        with:
          node-version: 14.16
          cache: "yarn"

      - name: Build @blockchain-com/constellation
        run: yarn workspace @blockchain-com/constellation build

      - name: NPM publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/constellation/package.json
          token: ${{ secrets.NPM_TOKEN }}
